version: '3.9'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    networks:
      - 'adminer-network'

  adminer:
    image: 'adminer'
    ports:
      - '8021:8080'
    environment:
      ADMINER_DEFAULT_SERVER: 'postgres'
      depends_on: 'postgres'
    networks:
      - 'adminer-network'

networks:
  adminer-network: